### ISSUE TITLE
proxy表名模糊查询结果不正确

### ISSUE THREAD

**Issue by chinahappyking** [chengshiwen/influx-proxy#10]
查询语句：
SELECT * FROM /agent.heartbeat/ WHERE  time > now() - 5m  limit 1 

版本：2.5.5

**Comment by chengshiwen** [comment]
目前确实还不支持模糊，只能针对精确的measurement

db和measurement的hash方法请参考：https://github.com/chengshiwen/influx-proxy/wiki?v=1#%E6%95%B0%E6%8D%AE%E5%AD%98%E5%82%A8%E4%BD%8D%E7%BD%AE

也欢迎优化~
