### ISSUE TITLE
the data rewrite success but the data file still here and the file size not change

### ISSUE THREAD

**Issue by SUNRise666s** [chengshiwen/influx-proxy#11]
truncate error: truncate F:\SYN\influx-proxy\data\influxdb-2-1.dat: Access is denied.

the data rewrite success but the data file still here and the file size not change

**Comment by chengshiwen** [comment]
Which version? And please check the permission

**Comment by SUNRise666s** [comment]
thank you for response！
It build on Windows and run on Windows

the error code is below.

你好，我编译的是windows的版本，是在windows运行

错误代码我调整如下便没报错


	/*err = fb.producer.Truncate(0)
	if err != nil {
		log.Print("truncate error: ", err)
		return
	}*/

	pathname := filepath.Join(fb.datadir, fb.filename)
	filename := pathname + ".dat"
	err = os.Truncate(filename,0)
	if err != nil {
		log.Print("truncate error: ", err)
		return
	}

**Comment by SUNRise666s** [comment]
Version is  the latest 2.5.5

**Comment by chengshiwen** [comment]
Thanks for your feedback! I will also check the changes in Linux and Mac

**Comment by SUNRise666s** [comment]
Thank you for response！Linux is ok and it's useful，I had Checked.By the way, it's not support for windows?

**Comment by chengshiwen** [comment]
I haven't tested it on Windows, while Linux has been verified by big data in the production environment of many customers for long time

**Comment by chengshiwen** [comment]
Close by https://github.com/chengshiwen/influx-proxy/commit/5340e795448dd563475a387033a58392bc253056
