### ISSUE TITLE
influx-proxy 2.5.6支持influxdb2.x的版本吗

### ISSUE THREAD

**Issue by yylstudy** [chengshiwen/influx-proxy#15]
请问一下 ，influx-proxy 2.5.6支持influxdb2.x的版本吗，谢谢

**Comment by chengshiwen** [comment]
不支持，计划下个大版本支持

**Comment by yylstudy** [comment]
好的 谢谢

**Comment by chengshiwen** [comment]
Relate issue: #20

**Comment by chengshiwen** [comment]
influxdb v2 已经基本支持，influx-proxy 3.0.0-preview 目前主要支持 api：
- query, write v2: `/api/v2/query`, `/api/v2/write`
- query, write v1 兼容: `/query`, `/write`

暂不支持（后续逐渐完善，需要事先手动在每个 influxdb 上创建好 org 和 bucket）：
- orgs: `/api/v2/orgs` 增删查改
- buckets: `/api/v2/buckets` 增删查改

详细请查看分支：[influxdb-v2](https://github.com/chengshiwen/influx-proxy/tree/influxdb-v2)

influx-proxy 3.0.0-preview：欢迎试用反馈👏🏻

- [influx-proxy-3.0.0-preview-darwin-amd64.tar.gz](https://github.com/chengshiwen/influx-proxy/files/8372617/influx-proxy-3.0.0-preview-darwin-amd64.tar.gz)
- [influx-proxy-3.0.0-preview-darwin-arm64.tar.gz](https://github.com/chengshiwen/influx-proxy/files/8372619/influx-proxy-3.0.0-preview-darwin-arm64.tar.gz)
- [influx-proxy-3.0.0-preview-linux-amd64.tar.gz](https://github.com/chengshiwen/influx-proxy/files/8372620/influx-proxy-3.0.0-preview-linux-amd64.tar.gz)
- [influx-proxy-3.0.0-preview-linux-arm64.tar.gz](https://github.com/chengshiwen/influx-proxy/files/8372621/influx-proxy-3.0.0-preview-linux-arm64.tar.gz)
- [influx-proxy-3.0.0-preview-windows-amd64.tar.gz](https://github.com/chengshiwen/influx-proxy/files/8372623/influx-proxy-3.0.0-preview-windows-amd64.tar.gz)
