### ISSUE TITLE
关于http://xxxx:7076/api/v1/prom/write报404的问题

### ISSUE THREAD

**Issue by wu9961** [chengshiwen/influx-proxy#16]
我在使用write或read接口时，发现通过proxy调用，会有404的问题，但是直接访问influxdb的端口，则不会有这个问题，请问是我的使用问题还是该功能还未对应，我使用的版本为influxdb 1.7.9

**Comment by wu9961** [comment]
用法请参考这里https://docs.influxdata.com/influxdb/v1.7/supported_protocols/prometheus/

**Comment by chengshiwen** [comment]
influx-proxy根据需求驱动开发，prometheus的两个接口之前没有收到需求，就暂时没有做支持，下个版本计划加上

**Comment by Jerry315** [comment]
加油啊，要是能支持prometheus就好了

**Comment by chengshiwen** [comment]
💪

**Comment by mingzizenmequ** [comment]
加油  你是最胖的！！！！

**Comment by shihao-lu** [comment]
加油！胖胖哒！！！

**Comment by chengshiwen** [comment]
开发 commit: 9608a9da25df130b205846c20099c63e3af78b1f
近期 2.5.8 将支持
