### ISSUE TITLE
rollback meta error: EOF

### ISSUE THREAD

**Issue by u2bo** [chengshiwen/influx-proxy#18]
2021/09/01 05:43:16.429379 backend.go:244: rewrite http error: http://influxdb-2:8086 testdb, length: 33964
2021/09/01 05:43:16.429460 backend.go:248: rollback meta error: EOF

**Comment by chengshiwen** [comment]
@u2bo proxy.json配置是怎么的呢？influxdb-2:8086的influxdb实例是否存在？这个错误是重写influxdb-2:8086失败

**Comment by u2bo** [comment]
有的{
    "circles": [
        {
            "name": "circle-1",
            "backends": [
                {
                    "name": "influxdb-1-1",
                    "url": "http://influxdb-1:8086",
                    "username": "",
                    "password": "",
                    "auth_encrypt": false
                }
            ]
        },
        {
            "name": "circle-2",
            "backends": [
                {
                    "name": "influxdb-2-1",
                    "url": "http://influxdb-2:8086",
                    "username": "",
                    "password": "",
                    "auth_encrypt": false
                }
            ]
        }
    ],
    "listen_addr": ":7076",
    "db_list": ["testdb"],
    "data_dir": "data",
    "tlog_dir": "log",
    "hash_key": "idx",
    "flush_size": 10000,
    "flush_time": 1,
    "check_interval": 1,
    "rewrite_interval": 10,
    "conn_pool_size": 20,
    "write_timeout": 10,
    "idle_timeout": 10,
    "username": "",
    "password": "",
    "auth_encrypt": false,
    "write_tracing": false,
    "query_tracing": false,
    "https_enabled": false,
    "https_cert": "",
    "https_key": ""
}

上面是我的配置，我这边都是跑在k8s中的，目前每个circle一个influxdb。
重写失败还会重写直到成功吗？

**Comment by chengshiwen** [comment]
k8s看你是怎么部署influxdb了，`influxdb-1:8086`和`influxdb-2:8086`，需要换成可访问的 fqdn 地址，例如 influxdb 只是通过 pod 部署，那就是 `pod-ip.pod-container-port`，如果是service+deployment，那么可以填写 `service-name.service-port`，如果是service+statefulset，那么填写 `pod-name.service-name.pod-container-port`

**Comment by u2bo** [comment]
influxdb-1:8086 是通的，前面可正常写入，后面就出现这种情况了

**Comment by chengshiwen** [comment]
麻烦贴下这个错误前后的所有完整日志

**Comment by u2bo** [comment]
write status code: 400, from: http://influxdb-2:8086
2021/09/02 10:02:20.361632 http.go:226: error response: {"error":"partial write: points beyond retention policy dropped=677"}
这种错误是？

**Comment by chengshiwen** [comment]
你设置了retention policy（保留策略），写入的部分点超过了rp的范围，这些点呗丢弃了
