### ISSUE TITLE
如何在grafana上展示influxdb的仪表盘？

### ISSUE THREAD

**Issue by lwfshensi** [chengshiwen/influx-proxy#19]
采用 grafana:5.2.4 对各个 influxdb 实例进行监控，执行导入仪表盘的脚本，将创建监控仪表盘。
这个仪表盘脚本在哪？

**Comment by chengshiwen** [comment]
@lwfshensi 
下载地址：https://github.com/chengshiwen/influx-proxy/wiki/assets/dashboard.json
导入方法：
- 导入 Dashboard: Create -> Import -> Upload .json File -> Import，将导入名为 InfluxDB Metrics 的 Dashboard
- 配置 Data Sources: Add data source -> 创建名字包含 influxdb 且 Type 为 InfluxDB 的数据源，将自动匹配该 Dashboard
