### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by mingzizenmequ** [chengshiwen/influx-proxy#21]
fatal: unable to access 'https://github.com/influxdata/influxdb1-client/': Failed connect to github.com:443; Connection refused

一直在这里报错！！

**Comment by mingzizenmequ** [comment]
大哥帮帮我把！！！！！！！！！！！！

**Comment by mingzizenmequ** [comment]
wo make 编译的时候

	fatal: unable to access 'https://github.com/tmc/grpc-websocket-proxy/': Failed connect to github.com:443; Connection refused
go: go.etcd.io/bbolt@v1.3.2: unknown revision v1.3.2
go: github.com/gorilla/websocket@v1.4.2: unknown revision v1.4.2
go: github.com/bketelsen/crypt@v0.0.3-0.20200106085610-5cbc8cc4026c: git fetch -f https://github.com/bketelsen/crypt refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /opt/module/go/gocode/pkg/mod/cache/vcs/8be8850b737807aced5ad95694b786fe96a00bf692489a46c79c01af25166430: exit status 128:
	fatal: unable to access 'https://github.com/bketelsen/crypt/': Failed connect to github.com:443; Connection refused
go: go.uber.org/atomic@v1.4.0: unknown revision v1.4.0
go: github.com/hashicorp/hcl@v1.0.0: unknown revision v1.0.0
go: github.com/spf13/afero@v1.1.2: unknown revision v1.1.2
go: github.com/coreos/go-systemd@v0.0.0-20190321100706-95778dfbb74e: git fetch -f https://github.com/coreos/go-systemd refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /opt/module/go/gocode/pkg/mod/cache/vcs/55443ccd12b639a5175355114c8465f0bf978e85db4d6afde60f05bde6b8451d: exit status 128:
	fatal: unable to access 'https://github.com/coreos/go-systemd/': Failed connect to github.com:443; Connection refused
go: github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0: unknown revision v1.2.0
go: github.com/spf13/jwalterweatherman@v1.0.0: unknown revision v1.0.0

怎么办   我想哭

**Comment by mingzizenmequ** [comment]
我编译的时候一直报错

**Comment by chengshiwen** [comment]
@mingzizenmequ 看起来是网络问题😂 你看看直接下载已经编译好的呢？https://github.com/chengshiwen/influx-proxy/releases/tag/v2.5.6

**Comment by mingzizenmequ** [comment]
好的 大哥
