### ISSUE TITLE
写入时指定rp的问题

### ISSUE THREAD

**Issue by firewolf2010** [chengshiwen/influx-proxy#22]
首先感谢作者非常棒的贡献！据我了解，shell909090/influx-proxy不支持写时指定rp。这个项目支持么？

**Comment by chengshiwen** [comment]
@firewolf2010 计划这个国庆支持/write接口指定rp

**Comment by firewolf2010** [comment]
Great！

**Comment by chengshiwen** [comment]
proxy进行全部保存，只有rewrite到influxdb时，influxdb会选择丢弃超过范围的数据

**Comment by firewolf2010** [comment]
@chengshiwen 明白了，感谢解答

**Comment by chengshiwen** [comment]
The [2.5.7 release](https://github.com/chengshiwen/influx-proxy/releases/tag/v2.5.7) has supported it
