### ISSUE TITLE
请问如何将过滤的sql释放出来，例如select into

### ISSUE THREAD

**Issue by java-orange** [chengshiwen/influx-proxy#26]
因为要做数据迁移，改变表名需要将旧的数据也迁移过来，所以使用了select into ,
然而被proxy 识别为危险sql， 被禁用掉，有什么方法可以释放开呢

**Comment by chengshiwen** [comment]
禁用代码在：
https://github.com/chengshiwen/influx-proxy/blob/c7772a1396890024f9a2c17e331f1e0c13d22570/backend/influxql.go#L301

需要注意的问题：
迁移使用`select into`改变measurement只会在当前influxdb实例上进行，对于跨实例则不行，会导致 新measurement 可能不在正确的influxdb实例上。例如，如果想把influxdb 1上的measurement-1改成measurement-2，但如果请求查询measurement-2的数据，influx-proxy计算 `db+measurement-2` 的hash值则可能会请求到influxdb2，就会发现没有measurement-2，导致出现问题

```
        ┌──────────────────┐
        │ writes & queries │
        └──────────────────┘
                 │
                 ▼
        ┌──────────────────┐
        │                  │
        │  InfluxDB Proxy  │
        │   (only http)    │
        │                  │
        └──────────────────┘
                 │
                 ▼
        ┌──────────────────┐
        │  db,measurement  │
        │ consistent hash  │
        └──────────────────┘
          |              |
        ┌─┼──────────────┘
        │ └────────────────┐
        ▼                  ▼
     Circle 1          Circle 2
  ┌────────────┐    ┌────────────┐
  │            │    │            │
  │ InfluxDB 1 │    │ InfluxDB 3 │
  │ InfluxDB 2 │    │ InfluxDB 4 │
  │            │    │            │
  └────────────┘    └────────────┘
```

目前最好的解决方案，是使用使用 `influx-tool export` 命令导出数据（导出后修改measurement名字），再使用 `influx-tool import` 或 `influx -import -path` 导入到 influx proxy:
    - **支持特性**：[influx-tool](https://github.com/chengshiwen/influx-tool) export 支持 `--measurement` 和 `--regexp-measurement` 导出特定 measurement，选项可以设置多次

**Comment by chengshiwen** [comment]
最近在做influxdb enterprise集群版的开源版本开发，可以支持解决select into问题@java-orange

**Comment by java-orange** [comment]
非常感谢回复，祝您生活开心

**Comment by fxmumu** [comment]
> 最近在做influxdb enterprise集群版的开源版本开发，可以支持解决select into问题@java-orange

作者您好，请问是出于什么原因未支持 continuous query 相关的操作呢？
我对 ifx 实现不熟悉，不知道是否是因为 ifx 的实现细节导致未支持 CQ 相关操作，所以发出此问题

**Comment by chengshiwen** [comment]
@fxmumu CQ 涉及 `select into` 语法，直接 `select into` 会导致结果表（例如measurement_b）和源表（例如measurement_a）在同一个实例上，但 influxdb proxy 代理，会根据 db 和 measurement 的 hash 值来确定写入或查询的 influxdb 实例，而实际上写入或查询 measurement_b 时， 根据 hash 确定的 influxdb 实例 很可能和 measurement_a 不是同一个实例，因此，查询 measurement_b 就可能查询不到结果

**Comment by chengshiwen** [comment]
> influxdb cluster 是按照 influxdb enterprise 来编写的，可以参考官方 influxdb enterprise 文档：
https://docs.influxdata.com/enterprise_influxdb/v1.8/concepts/clustering/
influxdb cluster支持高可用集群、更好的扩缩容、所有query语句

[InfluxDB Cluster v1.8.10-c1.0.0](https://github.com/chengshiwen/influxdb-cluster/releases/tag/v1.8.10-c1.0.0) 正式发布，参考 InfluxDB Enterprise 进行实现, 基于最新代码 InfluxDB v1.8.10 开发，旨在替换 InfluxDB Enterprise

项目地址：https://github.com/chengshiwen/influxdb-cluster

欢迎试用反馈👏🏻

@java-orange @fxmumu

**Comment by fxmumu** [comment]
> 

好的，我了解了，感谢

**Comment by fxmumu** [comment]
> @fxmumu CQ 涉及 `select into` 语法，直接 `select into` 会导致结果表（例如measurement_b）和源表（例如measurement_a）在同一个实例上，但 influxdb proxy 代理，会根据 db 和 measurement 的 hash 值来确定写入或查询的 influxdb 实例，而实际上写入或查询 measurement_b 时， 根据 hash 确定的 influxdb 实例 很可能和 measurement_a 不是同一个实例，因此，查询 measurement_b 就可能查询不到结果

好的，我了解了，感谢
