### ISSUE TITLE
Unbalanced load when using idx as the hash_key 

### ISSUE THREAD

**Issue by zaihuilvcha** [chengshiwen/influx-proxy#28]
Because the data volume of each measurement is not equal， some measurement with heavy data amount routed to one specific influxdb，and this influxdb instance is under much more stress than other instances.

I think it will be a common situation because different metrics have different reporting frequencies and data volumes……

If there is a more suitable way to configure, please advise.

**Comment by chengshiwen** [comment]
Before writing data, the data status of the measurement is unknown. The `hash_key` can only help balance the number of measurements, but it cannot achieve data load balancing.

To solve or mitigate this problem, possible solutions are as follows:
1. Divide the measurements with heavy data load according to the business and re-balance
2. I am developing influx-cluster, same as [influxdb enterprise](https://docs.influxdata.com/enterprise_influxdb/v1.9/concepts/clustering/), which will solve the current problems in influx-proxy better
