### ISSUE TITLE
请问为什么不支持linux-arm

### ISSUE THREAD

**Issue by Dosxiong** [chengshiwen/influx-proxy#30]
想要在linux-arm平台运行，发现influx-proxy-2.5.7-darwin-arm64 包无法运行
为什么没有linux-arm平台的二进制包，是代码里面有些东西没法适配吗？

**Comment by Dosxiong** [comment]
试了一下，可以通过添加linux/arm64去编译linux-arm包
TARGETS     := darwin/amd64 darwin/arm64 linux/amd64 windows/amd64 linux/arm64
测试可以正常运行。

**Comment by chengshiwen** [comment]
下次发版我也加入到Makefile里
