### ISSUE TITLE
请问进行resync和recover是直接将一个circle的数据完全覆盖到另外一个circle吗

### ISSUE THREAD

**Issue by Dosxiong** [chengshiwen/influx-proxy#31]
请问进行resync和recover是直接将一个circle的数据完全覆盖到另外一个circle吗，还是会对比差异，只写入另外一个circle丢失的部分。

**Comment by chengshiwen** [comment]
目前是全量，其中resync还可以指定tick时刻，只同步tick之后的数据

如果要对比差异，需要Anti-Entropy算法，这个是influxdb enterprise的特性：https://docs.influxdata.com/enterprise_influxdb/v1.8/administration/anti-entropy/

我将在后续实现这个特性

**Comment by hw2499** [comment]
提点建议，不知是否妥当。
1、全量：解决因需要而新增节点，用已有节点数据全量覆盖新节点。
2、增量：解决因节点宕机或数据同步机制出现问题，可根据两个节点的差异进行增量同步。目前不知道我们系统是如何实现的这个增量同步？（influxdb-proxy本身应该已经存储了同步数据日志，是否可以将每一节点的同步日志都独立出来，然后可指点从哪一份日志中进行增量恢复）
目前这个产品的现状，我能想到的就是当某节点宕机了，需要从一个健康的节点里按时间来导出一份数据然后同步到故障节点中。

**Comment by chengshiwen** [comment]
感谢建议！
1、全量：目前对新增或宕机恢复，是这个实现思路
2、增量：目前还没有增量的具体设计，influxdb-proxy只是缓存了写入失败的数据，等influxdb恢复后再尝试重写写入，因此并没有保存所有的；另外，同步数据日志可能不一定完全准确，我再详细想想

**Comment by chengshiwen** [comment]
Closed since no updates for long time.
