### ISSUE TITLE
about _internal database

### ISSUE THREAD

**Issue by xiaozaiyuji** [chengshiwen/influx-proxy#32]
In influx-proxy，when I open the _internal database  it show an error "InfluxData API responded with status code=BadRequest, response={"error":"database forbidden:_internal"} "。But when I open the single instance of influxdb ,It did not show this error,so why this show this error?

**Comment by chengshiwen** [comment]
`_internal` records the internal statistics of each influxdb instance. In influxdb proxy architecture, the proxy cannot determine the `_internal` of which influxdb instance should be accessed. Even if one is returned, the user or the client do not know which influxdb instance it is, so it is meaningless. The error `database forbidden` is used to prevent users from getting wrong results.

**Comment by xiaozaiyuji** [comment]
OK!Are you chinese? I am a Chinese and I have some question to ask.Can you tell me you contact?

**Comment by chengshiwen** [comment]
WeChat: Neo0103
