### ISSUE TITLE
请问Telegraf插件获取到的数据如何写入到influx-proxy中

### ISSUE THREAD

**Issue by yongjingwei** [chengshiwen/influx-proxy#33]
原来的数据是通过Telegraf写入到influxdb的，如果想用influx-proxy这套方案，如何把Telegraf拿到的数据写入到influx-proxy或他上层的nginx代理？

**Comment by chengshiwen** [comment]
只需要将Telegraf的配置文件中`[[outputs.influxdb]]`的`url`或`urls`的influxdb地址换为influx-proxy的地址即可，如果influx-proxy开启了认证，则相应的加上`username`和`password`即可，例如：
```
[[outputs.influxdb]]
  urls = "http://localhost:7076"
  skip_database_creation = true
  password = "monkey123"
```
或
```
[[outputs.influxdb]]
  url = "http://192.168.59.103:7076" # required.
  database = "telegraf" # required.
  precision = "s"
```

**Comment by chengshiwen** [comment]
连接到 Influx Proxy 和连接原生的 InfluxDB Server 没有显著区别 ([支持的查询语句列表](https://github.com/chengshiwen/influx-proxy/wiki?v=1#%E6%9F%A5%E8%AF%A2%E8%AF%AD%E5%8F%A5))，对上层客户端是透明的，上层应用可以像使用单机的 InfluxDB 一样使用

**Comment by chengshiwen** [comment]
Close since no updates for long time
