### ISSUE TITLE
请问influxdb v2什么时候能支持

### ISSUE THREAD

**Issue by yongjingwei** [chengshiwen/influx-proxy#34]

**Comment by chengshiwen** [comment]
@yongjingwei 预计3月底结束左右

**Comment by chengshiwen** [comment]
Duplicated with #20

**Comment by yongjingwei** [comment]
我会积极反馈问题的

**Comment by yongjingwei** [comment]
大佬，请问这个influx-proxy的开源规则是什么？

**Comment by chengshiwen** [comment]
> 大佬，请问这个influx-proxy的开源规则是什么？

你说的是开源许可证 License 吗？如是，目前是 MIT，几乎无限制

**Comment by yongjingwei** [comment]
大佬反馈下最近测试问题，目前v2版本读写通过nginx到influx-proxy到多个influxdb数据库读写都比较顺畅，通过停止某一个数据库查询数据一致性也正常，恢复挂掉的库数据也会被重新写进去，唯一目前似乎不支持的是用influxdb官方提供的influxdb-java-client或其他语言的客户端包连接时无法使用，似乎需要大佬支持SYSTEM INFORMATION ENDPOINTS下的
/influxdb/v2.0/api/health
/influxdb/v2.0/api/ping
/influxdb/v2.0/api/ready
/api/v2/
这几个api，这样整个单机版influxdb就可以无缝切换到您的集群版部署方案

**Comment by yongjingwei** [comment]
大佬反馈下最近测试问题，目前v2版本读写通过nginx到influx-proxy到多个influxdb数据库读写都比较顺畅，通过停止某一个数据库查询数据一致性也正常，恢复挂掉的库数据也会被重新写进去，唯一目前似乎不支持的是用influxdb官方提供的influxdb-java-client或其他语言的客户端包连接时无法使用，
SYSTEM INFORMATION ENDPOINTS下的
/influxdb/v2.0/api/health
/influxdb/v2.0/api/ping
/influxdb/v2.0/api/ready
/api/v2/
这几个api目前支持吗

**Comment by chengshiwen** [comment]
> 大佬反馈下最近测试问题，目前v2版本读写通过nginx到influx-proxy到多个influxdb数据库读写都比较顺畅，通过停止某一个数据库查询数据一致性也正常，恢复挂掉的库数据也会被重新写进去，唯一目前似乎不支持的是用influxdb官方提供的influxdb-java-client或其他语言的客户端包连接时无法使用， SYSTEM INFORMATION ENDPOINTS下的 /influxdb/v2.0/api/health /influxdb/v2.0/api/ping /influxdb/v2.0/api/ready /api/v2/ 这几个api目前支持吗

最近在做 [influxdb-cluster](https://github.com/chengshiwen/influxdb-cluster) 开发，这两天发布完看看你说的问题，以及支持你提到的 ENDPOINTS
