### ISSUE TITLE
【咨询】grafana接入influx-proxy

### ISSUE THREAD

**Issue by slzheng2017** [chengshiwen/influx-proxy#37]
你好：

目前使用grafana6.5.1版本，数据库使用influx-proxy（后端接influxdb集群）
有几个问题咨询下：
1. 我测试下来，influx-proxy似乎支持不了多条语句同时输入，例子如下。有计划支持多条语句同时输入的情况吗？
> SELECT mean("water_level") FROM "h2o_feet" WHERE time >= 1565998890092ms and time <= 1566006145978ms GROUP BY time(6m) fill(null);SELECT count("level description") FROM "h2o_feet" WHERE time >= 1565998890092ms and time <= 1566006145978ms GROUP BY time(6m) fill(null)
2. grafana在配置数据库时，只能填写一个url地址，按照教程中的架构，在2个influx-proxy前挂一个nginx，然后grafana接入该nginx。但这么做的话，nginx就成为单点了。咨询下：您这边有什么生产实践的建议，可以做到真正的高可用？

**Comment by chengshiwen** [comment]
1. 多语句计划在 [v2.6](https://github.com/chengshiwen/influx-proxy/wiki#v26) 支持
2. 生产当中，可能会使用硬件 F5，或者软件 LVS，或者多个 Nginx + Keepalived 等

**Comment by chengshiwen** [comment]
> influxdb cluster 是按照 influxdb enterprise 来编写的，可以参考官方 influxdb enterprise 文档：
https://docs.influxdata.com/enterprise_influxdb/v1.8/concepts/clustering/
influxdb cluster支持高可用集群、更好的扩缩容、所有query语句

[InfluxDB Cluster v1.8.10-c1.0.0](https://github.com/chengshiwen/influxdb-cluster/releases/tag/v1.8.10-c1.0.0) 正式发布，参考 InfluxDB Enterprise 进行实现, 基于最新代码 InfluxDB v1.8.10 开发，旨在替换 InfluxDB Enterprise

项目地址：https://github.com/chengshiwen/influxdb-cluster

欢迎试用反馈👏🏻
