### ISSUE TITLE
404报错

### ISSUE THREAD

**Issue by Juke-github** [chengshiwen/influx-proxy#38]
启动成功，为什么访问http://xxx.xxx.xx.xx:7076会报“404 page not found”，正确访问地址是多少

**Comment by chengshiwen** [comment]
http://xxx.xxx.xx.xx:7076 默认并没有代理路径，具体可以查看 [HTTP 接口](https://github.com/chengshiwen/influx-proxy/wiki#http-%E6%8E%A5%E5%8F%A3 )，例如

```
$ curl -G 'http://127.0.0.1:7076/query?db=mydb' --data-urlencode 'q=SELECT * FROM "mymeas"'

{"results":[{"statement_id":0,"series":[{"name":"mymeas","columns":["time","myfield","mytag1","mytag2"],"values":[["2017-03-01T00:16:18Z",33.1,null,null],["2017-03-01T00:17:18Z",12.4,"12","14"]]}]}]}
```

```
$ curl -i -X POST "http://127.0.0.1:7076/write?db=mydb&precision=s" --data-binary 'mymeas,mytag=1 myfield=90 1463683075'

HTTP/1.1 204 No Content
X-Influxdb-Version: 2.5.8
Date: Mon, 24 Aug 2020 19:54:33 GMT
```

**Comment by chengshiwen** [comment]
> influxdb cluster 是按照 influxdb enterprise 来编写的，可以参考官方 influxdb enterprise 文档：
https://docs.influxdata.com/enterprise_influxdb/v1.8/concepts/clustering/
influxdb cluster支持高可用集群、更好的扩缩容、所有query语句

[InfluxDB Cluster v1.8.10-c1.0.0](https://github.com/chengshiwen/influxdb-cluster/releases/tag/v1.8.10-c1.0.0) 正式发布，参考 InfluxDB Enterprise 进行实现, 基于最新代码 InfluxDB v1.8.10 开发，旨在替换 InfluxDB Enterprise

项目地址：https://github.com/chengshiwen/influxdb-cluster

欢迎试用反馈👏🏻
