### ISSUE TITLE
attachByValues的问题

### ISSUE THREAD

**Issue by slzheng2017** [chengshiwen/influx-proxy#40]
我在使用backend/executor.go attachByValues过程中发现如下问题：

1. 使用postman发送请求：select * from testtb，可以得到正确的结果。断点调试后发现value[0]是string类型（这个字段应该是time字段）
2. 使用influx客户端发送请求：select * from testtb，proxy panic。原因是value[0]是json.number类型

我的理解是，这么修改

valuesMap := make(map[interface{}]bool)
key := value[0]

您看下

**Comment by chengshiwen** [comment]
proxy 的版本或commit是哪个？`attachByValues` 是针对 `show retention policies`，不是 `select` 语句，所以这个问题的完整复现步骤是啥

**Comment by slzheng2017** [comment]
> proxy 的版本或commit是哪个？`attachByValues` 是针对 `show retention policies`，不是 `select` 语句，所以这个问题的完整复现步骤是啥

哦哦，如果attachByValues 只是针对 show retention policies，那应该没什么问题。我只是把他拿来另做他用了。

**Comment by chengshiwen** [comment]
<img width="823" alt="image" src="https://user-images.githubusercontent.com/4902714/165434474-28e5df29-61b4-41bf-bfe9-74e395e50516.png">

**Comment by chengshiwen** [comment]
我建议这样
```go
var key string
if jv, ok := value[0].(json.Number); ok {
	key = jv.String()
} else {
	key = value[0].(string)
}
```

**Comment by slzheng2017** [comment]
是的，我复用了你的`attachByValues`，使用的第一种建议
