### ISSUE TITLE
[咨询]influx-proxy性能与influxdb存储

### ISSUE THREAD

**Issue by slzheng2017** [chengshiwen/influx-proxy#41]
你好

1. 假设集群架构为：1influx-proxy+2集群（每个circle2个influxdb节点），influx-proxy提供的性能差不多是近乎单节点influxdb的2倍吗？（近乎线性？与influxdb节点成正比？）
2. 想咨询下生产上的经验，在存储方面的规划上，有没有资源分配上的经验可以借鉴。比如 每秒写入1w，在存储上需要规划多少足够？

**Comment by chengshiwen** [comment]
@slzheng2017 
1. 经过很多性能测试、以及大量客户生产环境验证，influx-proxy 写入性能是单机 influxdb 的 90% 左右，如果代理了多个influxdb，则在同一个 circle 里写入能力基本是线性叠加的，不同 circle 之间是并行写入的关系；查询性能也基本是如此
2. 给个参考，单个小硬件资源的 influxdb 实例，20min 写入 350290000 个点，每秒约 29w 的吞吐量，写完后磁盘数据文件占 2.0GB，而且 influxdb 会定期压缩，如果不再写入，后面磁盘数据文件 还会压得再小些。根据这个您可以测算和规划您场景的存储资源

另外欢迎加入 InfluxDB Cluster 社区交流群，问题可以通过群里沟通，具体方式详见：[社区 & 交流](https://github.com/chengshiwen/influxdb-cluster/wiki#%E7%A4%BE%E5%8C%BA--%E4%BA%A4%E6%B5%81)
