### ISSUE TITLE
circle中influxdb分片问题

### ISSUE THREAD

**Issue by Juke-github** [chengshiwen/influx-proxy#43]
一个数据库使用influx-proxy，是将每条数据根据算法分片到每个influxdb实例中？还是将数据库的每个表分片到每个influxdb中？我测试了一下，目前发现是将表分片到每个influxdb实例中，并不是将数据分片到每个influxdb中，这个结论不知道是否正确？若是按表分片，会不会导致每个influxdb实例的数据量很不均衡

**Comment by chengshiwen** [comment]
1、对 db+measurement 的值进行 hash，然后确定分到每个 circle 的某个 influxdb 实例上，也就是说，同一个db、同一个measurement(表) 的数据(点) 都在每个 circle 的同一个 influxdb 实例上，不同 circle 的关系是互为备份的关系。因此您提到的结论是正确的。
2、可能会导致数据量很不均衡，因为事先无法预知每个表的数据量规模，目前基本上每个 influxdb 的表的数量还是均衡的。事实上，无论是按表还是按照数据点进行分片，其实都可能出现数据量不均衡，因为这涉及到 hash 算法、写入数据的特征，其实在大数据中，也经常出现数据倾斜的问题，一般遇到这个问题，都需要重新找到合适分片方法，例如重写 hash 方法，或者加前缀，或者从业务上拆分等
