### ISSUE TITLE
有封装好的Helm Chart版本使用吗？

### ISSUE THREAD

**Issue by albertfeer** [chengshiwen/influx-proxy#44]

**Comment by chengshiwen** [comment]
暂时没有哈，可以参考 [docker quick](https://github.com/chengshiwen/influx-proxy/tree/master/docker/quick) 快速写一版 helm chart，helm 相关问题可以随时交流

**Comment by albertfeer** [comment]
收到，谢谢哈，近期做试验用的proxy.json。
再来参考docker-compose.yml写下chart。

在 2022年5月20日，17:59，Shiwen Cheng ***@***.***> 写道：

﻿

暂时没有哈，可以参考 docker quick<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fchengshiwen%2Finflux-proxy%2Ftree%2Fmaster%2Fdocker%2Fquick&data=05%7C01%7C%7C309b764125034087955708da3a477660%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637886375864354042%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yIDpj%2BqRl9MatJ0BKMYLq962bT%2Fl%2BbyCmp9UY0EPRJk%3D&reserved=0> 快速写一版 helm chart，helm 相关问题可以随时交流

**Comment by chengshiwen** [comment]
@albertfeer 已添加 [helm chart influx-proxy](https://github.com/influxtsdb/helm-charts/tree/master/charts/influx-proxy)
