### ISSUE TITLE
check backend if active may lead to many "backends unavailable" error in "one circle" situation

### ISSUE THREAD

**Issue by zaihuilvcha** [chengshiwen/influx-proxy#45]
e.g. QueryFromQL, Excutor.go:
```go
// pass non-active, rewriting or write-only.
	perms := rand.Perm(len(ip.Circles))
	for _, p := range perms {
		be := ip.Circles[p].GetBackend(key)
		if !be.IsActive() || be.IsRewriting() || be.IsWriteOnly() {
			continue
		}
		qr := be.Query(req, w, false)
		if qr.Err == nil {
			return qr.Body, nil
		}
		err = qr.Err
	}
```
If there is only one circle， when "be.IsActive" is false, data query will fail.  
The error of writting data also affects active status of one backend. If the write data fails, the subsequent read data will also fail
So I wonder if there is only one circle, may "be.IsActive" is not necessary？

**Comment by chengshiwen** [comment]
If the `key` (calculated by `db+measurement`) hits an inactive backend, `IsActive()` can actually be removed. However, under multiple circles, in order to unify the code, `IsActive()` is added.
