### ISSUE TITLE
支持 flux-dsl语句吗

### ISSUE THREAD

**Issue by lcwSeven** [chengshiwen/influx-proxy#46]
大佬是否支持使用influxDB的flux-dsl语句查询

**Comment by lcwSeven** [comment]
使用influxdb-v2时 使用的是官方提供的flux-dsl Java Api
` Flux.from("test")
                .range(-1L,ChronoUnit.DAYS)
                .filter(Restrictions.measurement().equal("measure"));`
解析出的语句为：
`from(bucket:"test")
	|> range(start:-1d)
	|> filter(fn: (r) => r["_measurement"] == "measure")`

r["_measurement"] 在influx-proxy中不能解析必须要写成 r._measurement

**Comment by chengshiwen** [comment]
没注意到这种情况，我见修复下

**Comment by chengshiwen** [comment]
https://github.com/chengshiwen/influx-proxy/commit/b20135635dd844a8451d6969db236e46ca223c40 已经支持修复

新的编译版本如下：
- [influx-proxy-3.0.0-preview-darwin-amd64.tar.gz](https://github.com/chengshiwen/influx-proxy/files/9039229/influx-proxy-3.0.0-preview-darwin-amd64.tar.gz)
- [influx-proxy-3.0.0-preview-darwin-arm64.tar.gz](https://github.com/chengshiwen/influx-proxy/files/9039236/influx-proxy-3.0.0-preview-darwin-arm64.tar.gz)
- [influx-proxy-3.0.0-preview-linux-amd64.tar.gz](https://github.com/chengshiwen/influx-proxy/files/9039237/influx-proxy-3.0.0-preview-linux-amd64.tar.gz)
- [influx-proxy-3.0.0-preview-linux-arm64.tar.gz](https://github.com/chengshiwen/influx-proxy/files/9039238/influx-proxy-3.0.0-preview-linux-arm64.tar.gz)
- [influx-proxy-3.0.0-preview-windows-amd64.tar.gz](https://github.com/chengshiwen/influx-proxy/files/9039239/influx-proxy-3.0.0-preview-windows-amd64.tar.gz)

**Comment by chengshiwen** [comment]
欢迎试用 2.5.10-preview 版本，支持 /api/v2 接口及 flux-dsl：

- [influx-proxy-2.5.10-preview-darwin-amd64.tar.gz](https://github.com/chengshiwen/influx-proxy/files/9565489/influx-proxy-2.5.10-preview-darwin-amd64.tar.gz)
- [influx-proxy-2.5.10-preview-darwin-arm64.tar.gz](https://github.com/chengshiwen/influx-proxy/files/9565504/influx-proxy-2.5.10-preview-darwin-arm64.tar.gz)
- [influx-proxy-2.5.10-preview-linux-amd64.tar.gz](https://github.com/chengshiwen/influx-proxy/files/9565514/influx-proxy-2.5.10-preview-linux-amd64.tar.gz)
- [influx-proxy-2.5.10-preview-linux-arm64.tar.gz](https://github.com/chengshiwen/influx-proxy/files/9565522/influx-proxy-2.5.10-preview-linux-arm64.tar.gz)
- [influx-proxy-2.5.10-preview-windows-amd64.tar.gz](https://github.com/chengshiwen/influx-proxy/files/9565535/influx-proxy-2.5.10-preview-windows-amd64.tar.gz)

**Comment by chengshiwen** [comment]
@lcwSeven
v2.5.10 已经正式发布：https://github.com/chengshiwen/influx-proxy/releases/tag/v2.5.10
docker 镜像：https://hub.docker.com/r/chengshiwen/influx-proxy
docker 命令：`docker pull chengshiwen/influx-proxy:2.5.10`
helm chart：https://github.com/influxtsdb/helm-charts/tree/master/charts/influx-proxy
