### ISSUE TITLE
Dose  influx-proxy support data auto rebalance  in a circle ?

### ISSUE THREAD

**Issue by rootdeep** [chengshiwen/influx-proxy#49]
If a influxdb instance is down in a circle, where the data of the influxdb will go ? 
Dose influx-proxy support data auto rebalance? or the data will be lost?

**Comment by chengshiwen** [comment]
> If a influxdb instance is down in a circle, where the data of the influxdb will go ?

influx-proxy will cache the data that fails to write to the local file, until influxdb reruns, influx-proxy will rewrite the failed data

> Dose influx-proxy support data auto rebalance? or the data will be lost?

Currently, manual rebalancing is required when influxdb is scaled up or down. The data will not be lost.

**Comment by rootdeep** [comment]
> > If a influxdb instance is down in a circle, where the data of the influxdb will go ?
> 
> influx-proxy will cache the data that fails to write to the local file, until influxdb reruns, influx-proxy will rewrite the failed data
> 
> > Dose influx-proxy support data auto rebalance? or the data will be lost?
> 
> Currently, manual rebalancing is required when influxdb is scaled up or down. The data will not be lost.

Dose support data replicas in a circle?

**Comment by chengshiwen** [comment]
> Dose support data replicas in a circle?

No. Circle and circle are replication of each other
