### ISSUE TITLE
该集群是否支持读写分离

### ISSUE THREAD

**Issue by yuebinqian** [chengshiwen/influx-proxy#52]
该集群是否支持读写分离

**Comment by chengshiwen** [comment]
写：每个节点都需要写；读：可以设置一些节点只写（write_only为true），即只写不读。暂时不支持读写分离

**Comment by yuebinqian** [comment]
大师，能否指定创建的数据库保存到某个节点里面

**Comment by yuebinqian** [comment]
如果没有设置节点只写的话，那读的话，是否会轮序或者随机的选中某个节点进行读取数据

**Comment by chengshiwen** [comment]
> 大师，能否指定创建的数据库保存到某个节点里面

目前不能

**Comment by chengshiwen** [comment]
> 如果没有设置节点只写的话，那读的话，是否会轮序或者随机的选中某个节点进行读取数据

会优先找健康的节点进行读取数据

**Comment by yuebinqian** [comment]
那请问单数据库建到多少的时候，才会水平扩展到Circle 2里面

**Comment by chengshiwen** [comment]
> 那请问单数据库建到多少的时候，才会水平扩展到Circle 2里面

只要配置了circle 2，就会同时写数据到circle 2里，查询的时候也会随机挑选健康的influxdb进行查询

**Comment by yuebinqian** [comment]
好的，请问连续查询目前能支持到，目前有块统计需要用到

**Comment by yuebinqian** [comment]
好的，请问连续查询目前能否支持到，目前有块统计需要用到

**Comment by chengshiwen** [comment]
influx-proxy 不支持 CQ，https://github.com/chengshiwen/influxdb-cluster 支持
