### ISSUE TITLE
v2的接口报404

### ISSUE THREAD

**Issue by tree-branch** [chengshiwen/influx-proxy#54]
# curl -G 'http://192.168.1.101:7076/query'
{"error":"empty query"}
# curl -G 'http://192.168.1.101:7076/api/v2/query'
404 page not found

部署的chengshiwen/influx-proxy:2.5.9
这是什么原因？

**Comment by chengshiwen** [comment]
第一个错误：是因为没有传递 q 参数，一般调用方法：
```
curl -G 'http://127.0.0.1:7076/query?db=db1' --data-urlencode 'q=select * from cpu1'
curl -G 'http://127.0.0.1:7076/query?db=db1&pretty=true' --data-urlencode 'q=select * from cpu1'
curl -G 'http://localhost:7076/query?pretty=true' --data-urlencode "db=mydb" --data-urlencode 'q=SELECT "value" FROM "cpu_load_short"'
curl -G 'http://localhost:8086/query?pretty=true' --data-urlencode "db=mydb" --data-urlencode "q=SELECT \"value\" FROM \"cpu_load_short\" WHERE \"region\"='us-west'"
```
第二个错误，目前 v2.5.x 尚不支持 /api/v2 接口，计划 v2.6.0 支持。注：v2.x 支持 influxdb v1 版本。

另外 v3.x 支持 [influxdb v2](https://github.com/chengshiwen/influx-proxy/tree/influxdb-v2)，已经支持 /api/v2 接口，可以参考 https://github.com/chengshiwen/influx-proxy/issues/46

**Comment by tree-branch** [comment]
非常感谢

**Comment by chengshiwen** [comment]
欢迎试用 2.5.10-preview 版本，支持 /api/v2 接口：

- [influx-proxy-2.5.10-preview-darwin-amd64.tar.gz](https://github.com/chengshiwen/influx-proxy/files/9565480/influx-proxy-2.5.10-preview-darwin-amd64.tar.gz)
- [influx-proxy-2.5.10-preview-darwin-arm64.tar.gz](https://github.com/chengshiwen/influx-proxy/files/9565487/influx-proxy-2.5.10-preview-darwin-arm64.tar.gz)
- [influx-proxy-2.5.10-preview-linux-amd64.tar.gz](https://github.com/chengshiwen/influx-proxy/files/9565500/influx-proxy-2.5.10-preview-linux-amd64.tar.gz)
- [influx-proxy-2.5.10-preview-linux-arm64.tar.gz](https://github.com/chengshiwen/influx-proxy/files/9565521/influx-proxy-2.5.10-preview-linux-arm64.tar.gz)
- [influx-proxy-2.5.10-preview-windows-amd64.tar.gz](https://github.com/chengshiwen/influx-proxy/files/9565541/influx-proxy-2.5.10-preview-windows-amd64.tar.gz)

**Comment by tree-branch** [comment]
好的 好的 等待你的镜像

**Comment by chengshiwen** [comment]
@tree-branch 
v2.5.10 已经正式发布：https://github.com/chengshiwen/influx-proxy/releases/tag/v2.5.10
docker 镜像：https://hub.docker.com/r/chengshiwen/influx-proxy
docker 命令：`docker pull chengshiwen/influx-proxy:2.5.10`
helm chart：https://github.com/influxtsdb/helm-charts/tree/master/charts/influx-proxy
