### ISSUE TITLE
Make 包时候出错

### ISSUE THREAD

**Issue by Rodifen** [chengshiwen/influx-proxy#55]
[root@localhost svolt]# cd influx-proxy-influxdb-v2
[root@localhost influx-proxy-influxdb-v2]# make
fatal: Not a git repository (or any of the parent directories): .git
GO111MODULE=on CGO_ENABLED=0 go build -o bin/influx-proxy -a -ldflags "-s -w -X github.com/chengshiwen/influx-proxy/backend.Version=3.0.0-preview -X github.com/chengshiwen/influx-proxy/backend.GitCommit= -X 'github.com/chengshiwen/influx-proxy/backend.BuildTime=2022-09-25 23:24:48'"
go: github.com/influxdata/influxdb1-client@v0.0.0-20220302092344-a9ab5670611c: Get "https://proxy.golang.org/github.com/influxdata/influxdb1-client/@v/v0.0.0-20220302092344-a9ab5670611c.mod": dial tcp 142.250.207.81:443: connect: connection refused
go: downloading github.com/influxdata/influxdb1-client v0.0.0-20220302092344-a9ab5670611c
go: downloading github.com/json-iterator/go v1.1.12
go: downloading github.com/panjf2000/ants/v2 v2.4.8
go: downloading github.com/spf13/viper v1.10.1
go: downloading stathat.com/c/consistent v1.0.0
go: github.com/influxdata/influxdb1-client@v0.0.0-20220302092344-a9ab5670611c: Get "https://proxy.golang.org/github.com/influxdata/influxdb1-client/@v/v0.0.0-20220302092344-a9ab5670611c.mod": dial tcp 142.250.207.81:443: connect: connection refused
make: *** [build] Error 1

**Comment by chengshiwen** [comment]
拉 github 依赖的问题，试试在 make 前执行，添加代理
```
go env -w GOPROXY=https://goproxy.cn,direct
```

**Comment by Rodifen** [comment]
好的，非常感谢

**Comment by Rodifen** [comment]
可以了。

**Comment by Rodifen** [comment]
v2 也是 git clone git://github.com/chengshiwen/influx-proxy.git ？
