### ISSUE TITLE
数据通过proxy写入失败，直写数据节点成功

### ISSUE THREAD

**Issue by xx280038830** [chengshiwen/influx-proxy#57]
proxy版本:3.0.0-preview
influxdb版本:v2.3.0
问题现象：
    目前有13个bucket，其中有1个突然发现只有极少数据写入成功(每分钟几K条写入，目前已经写了5G的数据量了，现在只有1~2条写入成功)。其他12个bucket都能正常写入。手动连接influxdb节点能正常写入，连接proxy写入后，状态码是返回正常的204，观察proxy日志也能抓到对应的写入请求且并没有发现异常，查询数据并没有写入进去。更换一个bucket名字后写入成功。(写入失败的bucket名称为vehicle.ipc，改为vehicle.ipc2后能够正常写入)。
proxy日志信息
![image](https://user-images.githubusercontent.com/39796191/195750600-53f183df-7fe0-4117-a946-46a7919736de.png)

**Comment by chengshiwen** [comment]
辛苦提供下：
- proxy 版本信息：./influx-proxy -version
- proxy.json 配置内容
- proxy data 目录下的文件截图，有没有大于 0 的 .dat 文件
- 数据写入的 client 是什么？如 influxdb-java-client
- influxdb 是否有错误日志

**Comment by xx280038830** [comment]
感谢回复。这是相关信息

- proxy版本：

<img width="710" alt="image" src="https://user-images.githubusercontent.com/39796191/196080017-1ba96c69-aa9a-4175-9def-77e1fb3d6470.png">

- proxy配置文件

{
    "circles": [
        {
            "name": "circle-1",
            "backends": [
                {
                    "name": "influxdb-1-1",
                    "url": "http://10.177.163.4:8086",
                    "token": "xxx"
                }
            ]
        },
        {
            "name": "circle-2",
            "backends": [
                {
                    "name": "influxdb-2-1",
                    "url": "http://10.23.47.29:8086",
                    "token": "xxx"
                }
            ]
        },
        {
            "name": "circle-3",
            "backends": [
                {
                    "name": "influxdb-3-1",
                    "url": "http://10.33.218.13:8086",
                    "token": "xxx"
                }
        ]
    }
    ],
    "dbrp": {
        "separator": "/",
        "mapping": {}
    },
    "listen_addr": ":7076",
    "data_dir": "data",
    "flush_size": 10000,
    "flush_time": 1,
    "check_interval": 1,
    "rewrite_interval": 10,
    "conn_pool_size": 20,
    "write_timeout": 10,
    "write_tracing": true,
    "query_tracing": true,
    "token": "578F68FC9EFDB61E",
    "https_enabled": false,
    "https_cert": "",
    "https_key": ""
}

- proxy data目录文件: dat文件没有数据

<img width="628" alt="image" src="https://user-images.githubusercontent.com/39796191/196080305-76ec55cd-20fe-4844-8202-1bb4a92e8d63.png">

- 数据写入的client
  业务使用的是influxdb-go-client.我这边使用http方式进行测试插入，例如
curl -v --request POST \
  'http://proxy-addredd:port/api/v2/write?org=mad&bucket=vehicle.ipc&precision=ms' \
    --header 'Authorization: Token 578F68FC9EFDB61E' \
    --data-binary '
memory,vin=lmtzsv025nc058574,vehicle_name=s20-271,vehicle_no=M2314 memory_available_mb=13474,memory_total_mb=31582,memory_usage_percent=57,memory_free_mb=2222.4444'

- infludb开启info级别日志统计，没有发现异常信息
- “现在只有1~2条写入成功” ，通过查询最近时间段的数据，发现memory表中会有零星几条最新的数据
      from(bucket: "vehicleipc2")
              |> range(start: -1000m)
              |> filter(fn: (r) => r._measurement == "memory")

**Comment by xx280038830** [comment]
抱歉，点错close了。
这个问题可以稳定复现

**Comment by chengshiwen** [comment]
按照刚才提供的数据，能复现不？或者再辛苦提供下复现步骤，我复现下🌹

**Comment by xx280038830** [comment]
按照这个数据是可以复现。

- 写proxy，bucket vehicle.ipc 返回码204，写入数据节点失败，同样的数据模型，更换bucket名字(例如vehicleipc2)后成功，

curl -v --request POST \
  'http://proxy-addredd:port/api/v2/write?org=mad&bucket=vehicle.ipc&precision=ms' \
    --header 'Authorization: Token 578F68FC9EFDB61E' \
    --data-binary '
memory,vin=lmtzsv025nc058574,vehicle_name=s20-271,vehicle_no=M2314 memory_available_mb=13474,memory_total_mb=31582,memory_usage_percent=57,memory_free_mb=2222.4444'

- 直写数据节点，bucket vehicle.ipc 写入成功
curl -v --request POST \
  'http://influxdb-node-address:port/api/v2/write?org=mad&bucket=vehicle.ipc&precision=ms' \
    --header 'Authorization: Token 578F68FC9EFDB61E' \
    --data-binary '
memory,vin=lmtzsv025nc058574,vehicle_name=s20-271,vehicle_no=M2314 memory_available_mb=13474,memory_total_mb=31582,memory_usage_percent=57,memory_free_mb=2222.4444'

**Comment by chengshiwen** [comment]
@xx280038830 我尝试复现，没有复现出来。辛苦执行下面的语句，然后它会返回 `mad`、`vehicle.ipc`、`memory` 实际存储的 influxdb，然后再直连检查下这个 influxdb 上数据是否存在？
```bash
curl 'http://127.0.0.1:7076/replica?org=mad&bucket=vehicle.ipc&meas=memory&pretty=true'
```

我目前的怀疑，可能是两个原因之一：
- 写入出现问题，因为数据类型冲突导致写入失败，例如 `memory_available_mb`、`memory_total_mb` 是 `integer` 时，需要再值后面添加 `i`，如果不加则默认是 `float`，同一个 shard 不能有两种数据类型，可以把 `range` 时间改为 0 看看再查询下
  - `memory,vehicle_name=s20-271,vehicle_no=M2314,vin=lmtzsv025nc058574 memory_available_mb=13474i,memory_free_mb=2222.4444,memory_total_mb=31582i,memory_usage_percent=57`
- 查询上出了问题，但是我不知道是如何查询的，例如是 `curl`、`influx query` 还是 `influxdb-go-client`，数据确实写入了，但是查询方式有问题

**Comment by chengshiwen** [comment]
Close this issue since no updates for long time
