### ISSUE TITLE
数据写入失败的时候，接口没有错误返回

### ISSUE THREAD

**Issue by hu08093446** [chengshiwen/influx-proxy#58]
最近在使用的时候发现，如果proxy向influxdb写入数据失败，/write接口是没有错误返回的，这样从业务上就无法知道本次数据写入是否成功
有没有办法可以解决这种问题

**Comment by chengshiwen** [comment]
proxy 设计之初采用 buffer 批量 flush 到 influxdb，如果写出现错误只能看 proxy 日志，所以目前暂时没有办法解决这个问题；后面可以考虑增加 阻塞模式，即不采用 buffer

另外，可以考虑 [influxdb-cluster](https://github.com/chengshiwen/influxdb-cluster)，则没有这个问题

**Comment by hu08093446** [comment]
了解了，感谢
