### ISSUE TITLE
influx-proxy-3.0.0-preview releases for influxdb v2

### ISSUE THREAD

**Issue by chengshiwen** [chengshiwen/influx-proxy#59]
[influx-proxy-3.0.0-preview-darwin-amd64.tar.gz](https://github.com/chengshiwen/influx-proxy/files/10072458/influx-proxy-3.0.0-preview-darwin-amd64.tar.gz)
[influx-proxy-3.0.0-preview-darwin-amd64.zip](https://github.com/chengshiwen/influx-proxy/files/10072459/influx-proxy-3.0.0-preview-darwin-amd64.zip)
[influx-proxy-3.0.0-preview-darwin-arm64.tar.gz](https://github.com/chengshiwen/influx-proxy/files/10072460/influx-proxy-3.0.0-preview-darwin-arm64.tar.gz)
[influx-proxy-3.0.0-preview-darwin-arm64.zip](https://github.com/chengshiwen/influx-proxy/files/10072461/influx-proxy-3.0.0-preview-darwin-arm64.zip)
[influx-proxy-3.0.0-preview-linux-amd64.tar.gz](https://github.com/chengshiwen/influx-proxy/files/10072462/influx-proxy-3.0.0-preview-linux-amd64.tar.gz)
[influx-proxy-3.0.0-preview-linux-amd64.zip](https://github.com/chengshiwen/influx-proxy/files/10072464/influx-proxy-3.0.0-preview-linux-amd64.zip)
[influx-proxy-3.0.0-preview-linux-arm64.tar.gz](https://github.com/chengshiwen/influx-proxy/files/10072465/influx-proxy-3.0.0-preview-linux-arm64.tar.gz)
[influx-proxy-3.0.0-preview-linux-arm64.zip](https://github.com/chengshiwen/influx-proxy/files/10072466/influx-proxy-3.0.0-preview-linux-arm64.zip)
[influx-proxy-3.0.0-preview-windows-amd64.tar.gz](https://github.com/chengshiwen/influx-proxy/files/10072467/influx-proxy-3.0.0-preview-windows-amd64.tar.gz)
[influx-proxy-3.0.0-preview-windows-amd64.zip](https://github.com/chengshiwen/influx-proxy/files/10072468/influx-proxy-3.0.0-preview-windows-amd64.zip)

**Comment by chen0815qh** [comment]
- 原来这里已经有你编译好的了，刚开始没注意到，不然就没必要自己编译了，不管怎样，再次感谢！ @chengshiwen

**Comment by chengshiwen** [comment]
[Release v3.0.0](https://github.com/chengshiwen/influx-proxy/releases/tag/v3.0.0) now officially released.
