### ISSUE TITLE
proxy 是否考虑增加后端influx 实例的用户透传能力？

### ISSUE THREAD

**Issue by wingerx** [chengshiwen/influx-proxy#62]
proxy 现在使用的用户认证方式比较单一，是不是不支持多用户的管理？这个有计划加强吗？比如不同database 需要创建不同的用户进行管理，是否可以使用原生influxdb 的用户体系呢？

**Comment by chengshiwen** [comment]
@wingerx 目前确实只有一种用户认证方式，如果要支持原生 influxdb 的用户体系，就和目前的技术方案存在不同，建议考虑 influxdb-cluster：https://github.com/chengshiwen/influxdb-cluster, 这个支持原生 influxdb 的用户体系

**Comment by wingerx** [comment]
了解了，多谢。influxdb-cluster 对于一个企业级使用会存在比较大的争议
