### ISSUE TITLE
 error response: {"code":"unauthorized","message":"Unauthorized"}

### ISSUE THREAD

**Issue by chen0815qh** [chengshiwen/influx-proxy#63]
多个数据库集群的时候，调用数据写入提示401，未授权，{"code":"unauthorized","message":"Unauthorized"}，采用的版本是Influx-proxy v2 版本（针对influxdb 2.x 的版本），每个节点配置了token也仍然报错

**Comment by chengshiwen** [comment]
@chen0815qh 配置过程是什么？influxdb v2每个节点必须有token才能访问，然后把这个token填入到proxy.json中，再启动 influx-proxy

**Comment by chen0815qh** [comment]
@chengshiwen 问题已经解决了，之所以出现上面那个问题，是因为我这边用的influx-proxy的版本不对（用的是https://github.com/chengshiwen/influx-proxy 主分支上你编译的ReleaseV2.5.10版本），我把你influxdb-v2 这个分支的代码clone后，编译了一个版本可以用了，目前我看编译出来的是influxproxy-3.0.0-preview 版本，感谢把这么好的项目开源出来，期待influx-proxy适配Influxdb 2.x 版本的后续更新。
