### ISSUE TITLE
为什么influxdb开启了身份验证后，proxy在配置填写了用户名和密码还是提示401，密码错误没填错~

### ISSUE THREAD

**Issue by GZMoMomo** [chengshiwen/influx-proxy#65]
通过curl能验证influxdb实例的身份信息，但在proxy里填写backends的用户名和密码 连接时还是提示401错误。

**Comment by chengshiwen** [comment]
一是确保proxy的版本是v2.5.x，二是确保修改了proxy.json后重启了proxy保证配置文件生效，三是检查用户、密码填写正确

**Comment by GZMoMomo** [comment]
> 一是确保proxy的版本是v2.5.x，二是确保修改了proxy.json后重启了proxy保证配置文件生效，三是检查用户、密码填写正确

我的版本是v2.5.10,重启了linux来重启proxy保证配置生效，检查了用户密码是最简单的admin 123456来确保正确，但通过启动influx-proxy还是提示2023/08/01 13:09:45.879814 http.go:204: ping status code: 401, the backend is http:***
我的配置文件是：
{
    "circles": [
        {
            "name": "circle-1",
            "backends": [
                {
                    "name": "influxdb-02",
                    "url": "http://****:8086",
                    "username":"admin",
                    "password": "123456",
                    "auth_encrypt": false,
                    "write_only": false
                }
            ]
        },
        {
            "name": "circle-2",
            "backends": [
                {
                    "name": "influxdb-03",
                    "url": "http://****:8086",
                    "username": "admin",
                    "password": "123456",
                    "auth_encrypt": false,
                    "write_only": false
                }
            ]
        }
    ],
    "listen_addr": ":7076",
    "db_list": [],
    "data_dir": "data",
    "tlog_dir": "log",
    "hash_key": "idx",
    "flush_size": 10000,
    "flush_time": 1,
    "check_interval": 1,
    "rewrite_interval": 10,
    "conn_pool_size": 20,
    "write_timeout": 10,
    "idle_timeout": 10,
    "username": "",
    "password": "",
    "auth_encrypt": false,
    "write_tracing": true,
    "query_tracing": true,
    "pprof_enabled": false,
    "https_enabled": false,
    "https_cert": "",
    "https_key": ""
}

**Comment by chengshiwen** [comment]
注意：influxdb 2.x 只能适配于 influxdb 1.x；对于 influxdb 2.x，需要使用 influx-proxy 3.x，可以查看 [influx-proxy-3.0.0-preview releases for influxdb v2](https://github.com/chengshiwen/influx-proxy/issues/59)
请确认下 influxdb 的版本，如果是 1.x，`/ping` 是不需要认证的，所以不会返回 `ping status code: 401`。

**Comment by GZMoMomo** [comment]
> 注意：influx-proxy 2.x 只能适配于 influxdb 1.x；对于 influxdb 2.x，需要使用 influx-proxy 3.x，可以查看 [influx-proxy-3.0.0-preview releases for influxdb v2](https://github.com/chengshiwen/influx-proxy/issues/59) 请确认下 influxdb 的版本，如果是 1.x，`/ping` 是不需要认证的，所以不会返回 `ping status code: 401`。

对的，我的influxdb是1.8版本，因为我在设置里开启了 ping-auth-enabled = true 所以会认证一次，我关了 ping-auth-enabled = true 虽然可以ping通，但查询时还是会提示ping status code: 401

**Comment by chengshiwen** [comment]
如果 `ping-auth-enable` 开启了，确实会报这个错误，但关了这个配置还会出现，那应该是 influxdb 修改配置后未重启导致

**Comment by chengshiwen** [comment]
`pprof-auth-enabled` 和 `ping-auth-enabled` 的支持，近期可以加上

**Comment by GZMoMomo** [comment]
> 如果 开启了，确实会报这个错误，但关了这个配置还会出现，那应该是 influxdb 修改配置后未重启导致`ping-auth-enable`

关了这个配置后，启动proxy不会出现401，但查询的时候就会提示401权限不足

**Comment by chengshiwen** [comment]
检查下 admin 的权限，提示 401 权限不足，这是 influxdb 直接返回的提示信息，需要检查下 influxdb 中 admin 的权限是否足够

**Comment by GZMoMomo** [comment]
> `pprof-auth-enabled`和 的支持，近期可以加上`ping-auth-enabled`



> 检查下 admin 的权限，提示 401 权限不足，这是 influxdb 直接返回的提示信息，需要检查下 influxdb 中 admin 的权限是否足够

admin账号 通过curl ”http://****/ping“ -u admin:123456 能访问成功，但在proxy里设置账号密码来访问就会提示401

**Comment by chengshiwen** [comment]
> 如果 `ping-auth-enable` 开启了，确实会报这个错误，但关了这个配置还会出现，那应该是 influxdb 修改配置后未重启导致

前面有提到，如果 `ping-auth-enable` 开启了，确实会报 401 这个错误，因为 proxy 还不支持 `ping-auth-enable` 开启的情况，下个版本考虑支持。

**Comment by GZMoMomo** [comment]
> > 如果 `ping-auth-enable` 开启了，确实会报这个错误，但关了这个配置还会出现，那应该是 influxdb 修改配置后未重启导致
> 
> 前面有提到，如果 `ping-auth-enable` 开启了，确实会报 401 这个错误，因为 proxy 还不支持 `ping-auth-enable` 开启的情况，下个版本考虑支持。

不是啦，如果关闭了`ping-auth-enable`后，开启proxy不会401报错，但查询的时候还是会验证失败401，不知道proxy是如何把账号密码作为参数传输的，不确定有没有把账号密码传过去。因为我使用curl可以正常访问实例数据库账号密码是没错误的。

**Comment by chengshiwen** [comment]
> 检查下 admin 的权限，提示 401 权限不足，这是 influxdb 直接返回的提示信息，需要检查下 influxdb 中 admin 的权限是否足够

前面有提到，如果是查询提示 401 权限不够，检查下 admin 的权限，提示 401 权限不足，这是 influxdb 直接返回的提示信息，需要检查下 influxdb 中 admin 的权限是否足够

**Comment by GZMoMomo** [comment]
> 

感谢作者耐心的解答~
