### ISSUE TITLE
.dat文件过大问题

### ISSUE THREAD

**Issue by 1435646097** [chengshiwen/influx-proxy#66]
您好，我在做测试的时候发现一个circle里面的influxdb实列都下线了数据会暂存在.dat文件中，如果这个circle里一直没有influxdb实列上线好像就会一直暂存在这里面直至写满磁盘，我看了配置文件的选项与ib.Flush()这个方法，好像并没有这文件大小方面的限制，是为了保持数据的一致性所以这样做的吗，如果出现磁盘写满就人为介入，毕竟数据优先，我的猜想是正确的吗？

**Comment by chengshiwen** [comment]
> 是为了保持数据的一致性所以这样做的吗

是的

> 如果出现磁盘写满就人为介入，毕竟数据优先，我的猜想是正确的吗？

正确

**Comment by 1435646097** [comment]
感谢您解答了我的疑惑，非常感谢。
