### ISSUE TITLE
read length error: EOF

### ISSUE THREAD

**Issue by rainbowwiki** [chengshiwen/influx-proxy#67]
您好，最近我们碰到了下面这个问题，下面是详细问题描述，问题可以复现

# 问题日志
1. proxy日志
```
2024/02/04 21:30:55.287846 http.go:239: http error: Post "http://10.247.165.77:8088/write?db=xxxxxx&rp=": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2024/02/04 21:30:55.287927 backend.go:186: write http error, url: http://10.247.165.77:8088, db: xxxxxx, rp: , plen: 36014
2024/02/04 21:31:02.704166 file.go:102: read length error: EOF
2024/02/04 21:31:02.704196 backend.go:238: rewrite read file error: EOF
2024/02/04 21:31:12.717414 file.go:102: read length error: EOF
2024/02/04 21:31:12.717456 backend.go:238: rewrite read file error: EOF

--
```

2. proxy & influxdb 日志
```
2024/02/04 21:30:55.287846 http.go:239: http error: Post "http://10.247.165.77:8088/write?db=xxxx&rp=": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2024/02/04 21:30:55.287927 backend.go:186: write http error, url: http://10.247.165.77:8088, db: xxxx, rp: , plen: 36014
2024/02/04 21:31:02.704166 file.go:102: read length error: EOF
2024/02/04 21:31:02.704196 backend.go:238: rewrite read file error: EOF
 
# influxdb log (10124497 is ns, request time cost)
 
[httpd] 172.17.0.5 - xxxxxx [04/Feb/2024:21:30:45 +0000] "POST /write?db=xxxxxx&rp= HTTP/1.1 " 500 20 "-" "Go-http-client/1.1" a7fa69cf-c3a4-11ee-a282-0242ac110004 10124497
ts=2024-02-04T21:30:55.656849Z lvl=error msg="[500] - \"timeout\"" log_id=0mvXbgq0000 service=httpd
```

# 分析
1. 通过日志我们发现 每当有influxdb 为**timeout**的情况时， 就会发生proxy那边的data/xxx.dat 持续累积，并且无法写入数据，proxy一直提示EOF （写入时间是10124497ns）

# 配置&版本信息
1. 我们是两个circle， 每个circle三个influxdb实例
2. 版本
- chengshiwen/influx-proxy:2.5.10
- influxdb:1.8.10 - oss

# QA
1. 这个是否是proxy的已知bug？ 我们已经调整了timeout -> 20s 正在观察中
2. 如果是单次timeout, 理论上不应该影响后续的写入， 感觉这个逻辑是不是有点问题 

期待您的回复！ 谢谢

**Comment by chengshiwen** [comment]
```
http.go:239: http error: Post "http://10.247.165.77:8088/write?db=xxxxxx&rp=": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
表明写入超时，对于返回非20x且非404（ErrBadRequest）的错误码，proxy 会将该数据压缩后写入到本地 .dat 文件中，等待 rewrite 线程重新读取 .dat 文件数据后再次写入到对应的 influxdb。
因此你看到 data/xxx.dat 持续累积，是正常现象。只有当 .dat 文件数据重写完成后，.dat 文件才会被清空，消费的 offset 偏移量会被记录到 data/xxx.rec 文件中。

为什么会出现 `file.go:102: read length error: EOF`，表明 rewrite 线程从 .dat 文件中读取数据是读到了文件末尾。
一是先检查下是否有 .dat 文件字节大小为 0 的，二是检查下文件的 rwx 权限，三是是否还有其他错误日志，光从目前提供的错误，还无法判断为什么会出现 EOF

```
[httpd] 172.17.0.5 - xxxxxx [04/Feb/2024:21:30:45 +0000] "POST /write?db=xxxxxx&rp= HTTP/1.1 " 500 20 "-" "Go-http-client/1.1" a7fa69cf-c3a4-11ee-a282-0242ac110004 10124497
```
`10124497` 单位是 `us`，所以换算下来是 `10.12s`，是 influxdb 默认的 `write-timeout` 时间。

现在回答你的 QA：

1. 这个是否是proxy的已知bug？ 我们已经调整了timeout -> 20s 正在观察中
回复：proxy一直提示EOF，现在信息不够，不确定是环境的问题，还是某种极端情况触发的 bug，曾经从未遇到过，按上述一、二、三进行排查

2. 如果是单次timeout, 理论上不应该影响后续的写入， 感觉这个逻辑是不是有点问题
回复：未影响后续写入，目前看日志为正常，`10124497` 单位是 `us`。

**Comment by rainbowwiki** [comment]
感谢回答！

追加描述下
1. 权限未曾变过， 之前一旦出现节点下线，处理逻辑完全正常， 上线后会自动写入 ，这次的情况有所不同，您说的几点我都已经check过， 都没问题

这种可能是未知bug，您那边可以timeout调小做下写入试下， 应该是可以重现的，当有timeout情况发生后, 后序proxy会一直报EOF

2. 单位是us， 我描述有误， 但是意思是一样的，达到了timeout时间点 ，
3. 一旦有EOF后， 缓存的数据不会被写入， 而且假如三个实例都有cache， 那么这三个缓存的数据都不会写入，实测是这样的，因为log都一样是EOF， 所以没有截图

**Comment by chengshiwen** [comment]
我测试下

**Comment by rainbowwiki** [comment]
你好， 请问下这边有什么进展吗？

**Comment by chengshiwen** [comment]
@rainbowwiki 没有复现，但在接下来发布的这个版本 2.5.11 优化了这个问题
