### ISSUE TITLE
influxdb v2.3.0+SNAPSHOT增加circle，存量数据无法同步

### ISSUE THREAD

**Issue by xuzili2018** [chengshiwen/influx-proxy#69]
使用resync会报databases为空

**Comment by chengshiwen** [comment]
> 使用resync会报databases为空

influx-proxy 2.x 只支持 influxdb 1.x，同时支持 resync 接口，如果报 databases 为空，可能需要先创建下相应的 db；influx-proxy 3.x 支持 influxdb 2.x，但不支持 resync 接口。

**Comment by xuzili2018** [comment]
感谢解答。那么使用influx-proxy 3.x 应该如何动态扩容circles且同步存量数据呢

**Comment by chengshiwen** [comment]
如果 circle 里 influxdb 数量相同的情况下，例如 circle1: [influxdb-1-1, influxdb-1-2, influxdb-1-3]，circle2: [influxdb-2-1, influxdb-2-2, influxdb-2-3]，那么可以对应位的influxdb的磁盘数据复制到新的circle里对应的influxdb，即influxdb-1-1的数据往influxdb-2-1复制，即influxdb-1-2的数据往influxdb-2-2复制
