### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by tixff** [chengshiwen/influx-proxy#7]
ERRO Running error: buildir: failed to load package : could not load export data: no export data for "github.com/modern-go/concurrent" 
make: *** [lint] Error 3

**Comment by chengshiwen** [comment]
@tixff How did you build it? What are your Golang version and operating system? And did you use the `make build` command?

**Comment by tixff** [comment]
@chengshiwen 1.16.2  我用的是make  按照quick start的操作来的

**Comment by tixff** [comment]
@chengshiwen 可以加个联系方式吗？这是我的google 邮箱 lixinlinti@gmail.com

**Comment by chengshiwen** [comment]
Already resolved
