### ISSUE TITLE
部署两个influxdb实例，通过influx-proxy做代理，停用其中一个influxdb实例后，导致influx-proxy无法访问

### ISSUE THREAD

**Issue by davis0511** [chengshiwen/influx-proxy#70]
#
<img width="351" alt="50" src="https://github.com/user-attachments/assets/cf046381-a2cc-497f-8e9c-c69b01ef2db0">

**Comment by davis0511** [comment]
@chengshiwen 请帮忙解答一下

**Comment by davis0511** [comment]
influx-proxy代理两个circle, 每个circle有一个influxdb实例，其中一个实例挂了，导致influx-proxy代理端口无法访问了，这样高可用也失效了

**Comment by chengshiwen** [comment]
influx-proxy 的版本？

**Comment by chengshiwen** [comment]
应该是 2.5.5 或 2.5.6，从 [2.5.7](https://github.com/chengshiwen/influx-proxy/releases/tag/v2.5.7) 开始对 backends unavailable 进行了优化，建议升级到最新版本 2.5.10

**Comment by davis0511** [comment]
是的，我目前用的版本是2.5.5



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Shiwen Cheng ***@***.***&gt;
发送时间: 2024年7月22日 18:45
收件人: chengshiwen/influx-proxy ***@***.***&gt;
抄送: davis0511 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [chengshiwen/influx-proxy] 部署两个influxdb实例，通过influx-proxy做代理，停用其中一个influxdb实例后，导致influx-proxy无法访问 (Issue #70)





 
应该是 2.5.5 或 2.5.6，从 2.5.7 开始对 backends unavailable 进行了优化，建议升级到最新版本 2.5.10

**Comment by chengshiwen** [comment]
2.5.5 对于 show 开头的查询语句，要求所有 influxdb 都在线，这个版本要求比较高，后来版本做了优化

**Comment by davis0511** [comment]
升级到2.5.10解决了问题，感谢
