### ISSUE TITLE
influxdb实例设置了密码权限，influx-proxy的proxy.json中auth_encrypt设置“true”， 通过命令访问可以连接，但是执行数据库命令却是没有权限，auth_encrypt改成“false",就可以了

### ISSUE THREAD

**Issue by davis0511** [chengshiwen/influx-proxy#71]
![image](https://github.com/user-attachments/assets/905787d5-c969-4818-afc8-b2f1db776bde)
influx-proxy: v2.5.10

![image](https://github.com/user-attachments/assets/933ae2ba-a97e-408e-a7e3-e49db9393527)

**Comment by chengshiwen** [comment]
backends 里的 `username` 和 `password` 填写为对应 influxdb 的 账密，`auth_encrypt` 不用填写，这个是用于认证信息加密的

**Comment by chengshiwen** [comment]
详见[字段说明](https://github.com/chengshiwen/influx-proxy/wiki#%E5%AD%97%E6%AE%B5%E8%AF%B4%E6%98%8E)

<img width="804" alt="image" src="https://github.com/user-attachments/assets/a0d84c25-7b29-46d7-9590-01ddf5a9f19c">
