### ISSUE TITLE
hash 路由设置：关于influx proxy hash key 以及shard key

### ISSUE THREAD

**Issue by rainbowwiki** [chengshiwen/influx-proxy#73]
您好， 感谢提醒，首先庆祝这个hash_key 以及shard_key 功能的发布！ 感谢！

但是关于这个hash策略，没看明白具体怎么应用，能帮忙举个例子吗？

假设proxy 配置了如下配置， 那这个是如何控制数据写到哪里的？例如我有两个circle 每个circle有三个实例，
```
circle1
      instance1
      instance2
      instance3
circle2
      instance1
      instance2
      instance3
```
有这样的数据如下：
```
memory,host=host5 used=6471i
network,host=host2 bytes_recv=8707i
disk,host=host5 used_percent=89.37
cpu,host=host5 usage_user=0.2
disk,host=host1 read_bytes=7351i
memory,host=host3 free=8527i
network,host=host2 errors=645i
network,host=host5 bytes_recv=3984i
memory,host=host3 free=5408i
memory,host=host3 used=8950i
disk,host=host5 read_bytes=7076i
```

我应该怎么样配置可以让cpu这张表写到instance1 , memory 写到instance2，disk写到instance3 呢？ 这个可以实现吗？

_Originally posted by @rainbowwiki in https://github.com/chengshiwen/influx-proxy/issues/68#issuecomment-2291017815_

**Comment by chengshiwen** [comment]
对于特定规则，如某个 measurement 必须写到某个 influxdb 实例，目前不支持，v2.5.x 仅支持 hash 路由规则。v2.6.x 则计划支持 hash 路由和自定义规则，例如前缀匹配规则。

对于你的需求，目前可以通过 `influx-tool hashdist -n 3 -d <database> -m <measurement> -k <hash_key> -K <shard_key>` 命令，通过设置合适的 `hash_key` 和 `shard_key`，让这几个 measurement 表分到不同的 instance 里，然后可以执行 `influx-tool hashdist -n 3 -f <file> -k <hash_key> -K <shard_key> -D -` 测试下，所有数据分布是否均匀

`hash_key` 模板需要包含 `%idx`，你可以设置类似 `backend-%idx` 的模板；`shard_key` 模板需要包含 `%db` 和 `%mm`，你可以设置类似 `shard-%db-%mm` 的模板，只要找到合适的 `hash_key` 和 `shard_key` 即可

**Comment by rainbowwiki** [comment]
谢谢～
