### ISSUE TITLE
想了解最新更新了什么功能

### ISSUE THREAD

**Issue by yongjingwei1989** [chengshiwen/influx-proxy#74]
你好，大牛，请问这次更新增加了什么功能，有说明没

**Comment by chengshiwen** [comment]
英文 Release：
- https://github.com/chengshiwen/influx-proxy/releases/tag/v2.5.11
- https://github.com/chengshiwen/influx-proxy/releases/tag/v2.5.12

中文 发版说明：
- https://github.com/chengshiwen/influx-proxy/wiki#v2511
- https://github.com/chengshiwen/influx-proxy/wiki#v2512

**Comment by yongjingwei1989** [comment]
是v2.0也支持了hash_key，shard_key，我记着原来似乎v2.0不支持 
![image](https://github.com/user-attachments/assets/2546d393-24fb-4db5-83af-e193004035be)

**Comment by chengshiwen** [comment]
@yongjingwei1989 是的，influx-proxy v3.0.0 也支持，相比两年前 v3.0.0-preview 版本，本次修改的 commits 记录如下：
https://github.com/chengshiwen/influx-proxy/compare/d3d467e9379e1b010506f82f2e22fce93b894e39...v3.0.0
<img width="599" alt="image" src="https://github.com/user-attachments/assets/7c9f0c9d-8f77-40c8-9690-487c854153c7">
