### ISSUE TITLE
x-msgpack: v1 的 query 接口报 400

### ISSUE THREAD

**Issue by Codeyear8** [chengshiwen/influx-proxy#75]
influx的v1的API当中部分支持 content-Type：application/x-msgpack，按照文档完成初始化v1.8集群后测试 curl -XGET -H "Accept:application/x-msgpack" http://ip:port/query?u=admin&p=admin&dn=testdb&q=SHOW+MEASUREMENTS 报错。想确认下是否不支持。

**Comment by chengshiwen** [comment]
目前暂不支持 x-msgpack
